import React from "react";
import {
  RecipeListContainer,
  RecipeListHead,
  RecipeListHeadRow,
  RecipeListHeadInfo,
  RecipeListBody,
  RecipeListBodyRow,
  RecipeListBodyDesc,
  RecipeListBodyDescTitle,
  RecipeListBodyDescContent,
} from "./RecipeList.element";

const RecipeList = () => {
  return (
    <RecipeListContainer>
      <RecipeListHeadRow>
        <RecipeListHeadInfo>主題</RecipeListHeadInfo>
        <RecipeListHeadInfo>留言數</RecipeListHeadInfo>
        <RecipeListHeadInfo>分類</RecipeListHeadInfo>
      </RecipeListHeadRow>
      <RecipeListBody>
        <RecipeListBodyRow>
          <RecipeListBodyDesc>
            <RecipeListBodyDescTitle>琴酒</RecipeListBodyDescTitle>
            <RecipeListBodyDescContent>好喝喔</RecipeListBodyDescContent>
          </RecipeListBodyDesc>
          <RecipeListBodyDesc>3</RecipeListBodyDesc>
          <RecipeListBodyDesc>琴酒</RecipeListBodyDesc>
        </RecipeListBodyRow>
        <RecipeListBodyRow>
          <RecipeListBodyDesc>
            <RecipeListBodyDescTitle>好喝的酒</RecipeListBodyDescTitle>
            <RecipeListBodyDescContent>
              gfdgfdhgfhgfchfdfbvx
            </RecipeListBodyDescContent>
          </RecipeListBodyDesc>
          <RecipeListBodyDesc>3</RecipeListBodyDesc>
          <RecipeListBodyDesc>琴酒</RecipeListBodyDesc>
        </RecipeListBodyRow>

        <RecipeListBodyRow>
          <RecipeListBodyDesc>
            <RecipeListBodyDescTitle>好喝的酒</RecipeListBodyDescTitle>
            <RecipeListBodyDescContent>
              gfdgfdhgfhgfchfdfbvx
            </RecipeListBodyDescContent>
          </RecipeListBodyDesc>
          <RecipeListBodyDesc>3</RecipeListBodyDesc>
          <RecipeListBodyDesc>琴酒</RecipeListBodyDesc>
        </RecipeListBodyRow>

        <RecipeListBodyRow>
          <RecipeListBodyDesc>
            <RecipeListBodyDescTitle>好喝的酒</RecipeListBodyDescTitle>
            <RecipeListBodyDescContent>
              gfdgfdhgfhgfchfdfbvx
            </RecipeListBodyDescContent>
          </RecipeListBodyDesc>
          <RecipeListBodyDesc>3</RecipeListBodyDesc>
          <RecipeListBodyDesc>琴酒</RecipeListBodyDesc>
        </RecipeListBodyRow>
        <RecipeListBodyRow>
          <RecipeListBodyDesc>
            <RecipeListBodyDescTitle>好喝的酒</RecipeListBodyDescTitle>
            <RecipeListBodyDescContent>
              gfdgfdhgfhgfchfdfbvx
            </RecipeListBodyDescContent>
          </RecipeListBodyDesc>
          <RecipeListBodyDesc>3</RecipeListBodyDesc>
          <RecipeListBodyDesc>琴酒</RecipeListBodyDesc>
        </RecipeListBodyRow>
        <RecipeListBodyRow>
          <RecipeListBodyDesc>
            <RecipeListBodyDescTitle>好喝的酒</RecipeListBodyDescTitle>
            <RecipeListBodyDescContent>
              gfdgfdhgfhgfchfdfbvx
            </RecipeListBodyDescContent>
          </RecipeListBodyDesc>
          <RecipeListBodyDesc>3</RecipeListBodyDesc>
          <RecipeListBodyDesc>琴酒</RecipeListBodyDesc>
        </RecipeListBodyRow>
        <RecipeListBodyRow>
          <RecipeListBodyDesc>
            <RecipeListBodyDescTitle>好喝的酒</RecipeListBodyDescTitle>
            <RecipeListBodyDescContent>
              gfdgfdhgfhgfchfdfbvx
            </RecipeListBodyDescContent>
          </RecipeListBodyDesc>
          <RecipeListBodyDesc>3</RecipeListBodyDesc>
          <RecipeListBodyDesc>琴酒</RecipeListBodyDesc>
        </RecipeListBodyRow>
        <RecipeListBodyRow>
          <RecipeListBodyDesc>
            <RecipeListBodyDescTitle>好喝的酒</RecipeListBodyDescTitle>
            <RecipeListBodyDescContent>
              gfdgfdhgfhgfchfdfbvx
            </RecipeListBodyDescContent>
          </RecipeListBodyDesc>
          <RecipeListBodyDesc>3</RecipeListBodyDesc>
          <RecipeListBodyDesc>琴酒</RecipeListBodyDesc>
        </RecipeListBodyRow>
        <RecipeListBodyRow>
          <RecipeListBodyDesc>
            <RecipeListBodyDescTitle>好喝的酒</RecipeListBodyDescTitle>
            <RecipeListBodyDescContent>
              gfdgfdhgfhgfchfdfbvx
            </RecipeListBodyDescContent>
          </RecipeListBodyDesc>
          <RecipeListBodyDesc>3</RecipeListBodyDesc>
          <RecipeListBodyDesc>琴酒</RecipeListBodyDesc>
        </RecipeListBodyRow>
                <RecipeListBodyRow>
          <RecipeListBodyDesc>
            <RecipeListBodyDescTitle>好喝的酒</RecipeListBodyDescTitle>
            <RecipeListBodyDescContent>
              gfdgfdhgfhgfchfdfbvx
            </RecipeListBodyDescContent>
          </RecipeListBodyDesc>
          <RecipeListBodyDesc>3</RecipeListBodyDesc>
          <RecipeListBodyDesc>琴酒</RecipeListBodyDesc>
        </RecipeListBodyRow>
        
      </RecipeListBody>
    </RecipeListContainer>
  );
};

export default RecipeList;
